plugins {
    id 'com.android.library'
}

android {
    namespace 'com.example.unityadsplugin'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.unity3d.ads:unity-ads:4.9.2'
    compileOnly fileTree(dir: 'libs', include: ['godot-lib*.aar'])
}
